name: TowardsLife
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_hooks: 0.15.0
  snapping_sheet: 2.0.1
  flutter_tts:
  cloud_firestore:
  get:
  get_storage:
  firebase_core: 0.5.2
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview:
  lint:
  test:
  flutter_launcher_icons: "^0.7.5"
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Towards Life"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/tl.png"

flutter:
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/

  fonts:
    - family: NotoSansTamil
      fonts:
        - asset: assets/fonts/NotoSansTamil-Regular.ttf
        - asset: assets/fonts/NotoSansTamil-Bold.ttf
          weight: 700
    - family: ArimaMadurai
      fonts:
        - asset: assets/fonts/ArimaMadurai-Regular.ttf
        - asset: assets/fonts/ArimaMadurai-Medium.ttf
          weight: 700